language: python
python:
  - "3.6"

install:
  - pip install codecov
  - pip install pytest pytest-cov pytest-asyncio
  - pip install -e .
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=./

after_success:
  - codecov