language: python
python:
  - "3.6"

addons:
  apt:
    packages:
    - firefox
    - time

before_install:
  - >
    sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz &&
    sudo tar -xvzf geckodriver* &&
    sudo chmod +x geckodriver &&
    sudo mv geckodriver /usr/local/bin/

install:
  - pip install codecov
  - pip install pytest pytest-cov pytest-asyncio
  - pip install -e .
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=./

after_success:
  - codecov