version: "3"

services:
  gisi:
    container_name: Gisi
    image: giesela/gisi
    build: .
    restart: always
    volumes:
      - gisi:/gisi/data
      - gisi:/gisi/logs
    networks:
      - backend
    environment:
      - TOKEN
      - MONGO_URI=mongodb://mongodb:27017
      - CHROME_WS=ws://browserless:3000
      - GOOGLE_API_KEY
      - SENTRY_DSN
  mongodb:
    container_name: MongoDB
    image: mongo
    restart: always
    networks:
      - backend
    volumes:
      - db:/data

  browserless:
    container_name: Browserless
    image: browserless/chrome
    restart: always
    networks:
      - backend
    expose:
      - 3000
    environment:
      - MAX_CONCURRENT_SESSIONS=2
      - MAX_QUEUE_LENGTH=3
      - CONNECTION_TIMEOUT=120000

volumes:
  db: {}
  gisi: {}

networks:
  backend: {}