version: "3"
services:
  gisi:
    image: siku2/Gisi:navi
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp
  mongo:
    image: mongo:3.7
    volumes:
      - mongo:/data/db
    expose:
      - "27017"
volumes:
  mongo: